version: '3.8'

services:
  app:
    build: ./
    image: judykimsohui/nemo-be:latest
    container_name: nemo-be
    ports:
      - "5000:8080"
    volumes:
      - ~/app/config/application.yml:/app/application.yml
      - ~/app/static:/app/static
    environment:
      FILE_UPLOAD_DIR: /app/static
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - nemo-mysql
    networks:
      - nemo-net

  nemo-mysql:
    image: judykimsohui/nemo-mysql:latest
    container_name: nemo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: OceanAcademyDevDB
    ports:
      - "3307:3306"
    volumes:
      - ./db-data:/var/lib/mysql
      - ./rds_backup.sql:/docker-entrypoint-initdb.d/rds_backup.sql
    networks:
      - nemo-net

volumes:
  db-data:

networks:
  nemo-net:
    driver: bridge
