version: '3.8'

services:
  app:
    build: ./
    image: judykimsohui/nemo-be:latest
    container_name: nemo-be
    ports:
      - "5000:8080"
    volumes:
      - ~/app/config/application.yml:/app/application.yml
      - ~/app/static:/app/static
    environment:
      FILE_UPLOAD_DIR: /app/static
    depends_on:
      - nemo-mysql
    networks:
      - nemo-net

  nemo-mysql:
    image: mysql:5.7
    container_name: nemo-mysql
    ports:
      - "3307:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_PASSWORD}
      MYSQL_DATABASE: OceanAcademyDevDB
    networks:
      - nemo-net

volumes:
  db-data:

networks:
  nemo-net:
    driver: bridge
