spring:
  datasource:
    url: jdbc:mysql://oceanacademydb.cx0u8okkguoh.ap-northeast-2.rds.amazonaws.com:3306/OceanAcademyDB
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: redis-prod
      port: 6379

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: https://yourdomain.com/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
