spring:
    profiles:
        active: local
    jackson:
        property-naming-strategy: SNAKE_CASE
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
        properties:
            hibernate:
                format_sql: true
                highlight_sql: true

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 5
        url: jdbc:mysql://oceanacademydb.cx0u8okkguoh.ap-northeast-2.rds.amazonaws.com:3306/OceanAcademyDB
        username: root
        password: Nemo0325!!

    security:
        oauth2:
            client:
                registration:
                    kakao:
                        client-id: 7d7c12cfa0f81fb0e951a7c1ca8f49db
                        client-secret: EHZZ7q9KdKvLtEMlskLwk1iM5bpQUSpr
                        redirect-uri: http://localhost:8080/login/oauth2/code/kakao
                        authorization-grant-type: authorization_code
                        scope: profile_nickname, profile_image
                        client-authentication-method: POST
                        client-name: Kakao
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
    logging:
        level:
            org.hibernate.SQL: debug

file:
    upload-dir: src/main/resources/static

servlet:
    session:
        tracking-modes: cookie