spring:
  datasource:
    url: jdbc:mysql://oceanacademydb.cx0u8okkguoh.ap-northeast-2.rds.amazonaws.com:3306/OceanAcademyDB
    username: root
    password: Nemo0325!!
    driver-class-name: com.mysql.cj.jdbc.Driver


  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
