spring:
    profiles:
        active: local
    jackson:
        property-naming-strategy: SNAKE_CASE

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 5

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
        properties:
            hibernate:
                format_sql: true
                highlight_sql: true

logging:
    level:
        org.hibernate.SQL: debug

file:
    upload-dir: src/main/resources/static



#cloud:
#    aws:
#        s3:
#            bucket-name: ${S3_BUCKET_NAME}
#            access-key: ${S3_ACCESS_KEY}
#            secret-key: ${S3_SECRET_KEY}
#            region: ${S3_REGION}
